name: SnipClip
options:
  bundleIdPrefix: com.snipclip
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "15"

targets:
  SnipClip:
    type: application
    platform: macOS
    sources:
      - path: SnipClip
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.snipclip.mac
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "4"
        SWIFT_VERSION: "5.9"
        MACOSX_DEPLOYMENT_TARGET: "13.0"
        INFOPLIST_FILE: SnipClip/Info.plist
        ENABLE_HARDENED_RUNTIME: YES
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: Q8BH8C2Y28
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      configs:
        Debug:
          CODE_SIGN_ENTITLEMENTS: SnipClip/SnipClip-Debug.entitlements
        Release:
          CODE_SIGN_ENTITLEMENTS: SnipClip/SnipClip.entitlements

schemes:
  SnipClip:
    build:
      targets:
        SnipClip: all
    run:
      config: Debug
      storeKitConfiguration: SnipClip/SnipClip.storekit
