name: SnipClip
options:
  bundleIdPrefix: com.lukewelch
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "15"

targets:
  SnipClip:
    type: application
    platform: macOS
    sources:
      - path: SnipClip
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.lukewelch.snipclip
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "5.9"
        MACOSX_DEPLOYMENT_TARGET: "13.0"
        CODE_SIGN_ENTITLEMENTS: SnipClip/SnipClip.entitlements
        INFOPLIST_FILE: SnipClip/Info.plist
        ENABLE_HARDENED_RUNTIME: YES
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: NZK4VD7566
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon

schemes:
  SnipClip:
    build:
      targets:
        SnipClip: all
    run:
      config: Debug
      storeKitConfiguration: SnipClip/SnipClip.storekit
